version: 2

sources: 
  - name: raw
    schema: gz_raw_data
    description: data from Greeenweez used to create a table for conducting basket analysis 
    tables: 
      - name: sales
        identifier: raw_gz_sales 
        description: sales of Greenweez / we have one row per product_id found in each orders_id
        freshness: 
          warn_after: {count: 90, period: day}
        loaded_at_field: CAST(date_date AS timestamp)
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"           
        columns:
          - name: date_date
            description: date of purchase
          - name: orders_id
            description: id for each order
          - name: pdt_id
            description: id for each product
          - name: revenue
            description: revenue for each product in the order
          - name: quantity
            description: quantity of the product in the order
      - name: product
        identifier: raw_gz_product
        description: products of Greenweez/ one row per product
        columns:
          - name: products_id
            description: unique id for each product
            tests: 
              - unique
              - not_null
          - name: purchse_price
            description: purchase price for each product
      - name: ship
        identifier: raw_gz_ship
        description: shipping information / one row per order 
        columns: 
          - name: orders_id
            description: unique id for each order
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: shipping fee for each order
          - name: logcost
            description: logistics cost for each order
          - name: ship_cost
            description: shipping cost for each order
      - name: ads_adwords
        identifier: raw_gz_adwords
        description: campaigns on adwords/ one row per day with campaign key and name 
        columns: 
          - name: date_date
            description: date 
          - name: paid_source
            description: campaign platform/ adwords
          - name: campaign_key
            description: key of the campaign
          - name: camPGN_name
            description: name of the campaign
          - name: ads_cost
            description: advertisement cost for the campaign on a specific day
          - name: impression
            description: number of impressions 
          - name: click
            description: number of clicks 
      - name: ads_bing
        identifier: raw_gz_bing
        description: campaigns on bing/ one row per day with campaign key and name   
        columns: 
          - name: date_date
            description: date 
          - name: paid_source
            description: campaign platform/ bing 
          - name: campaign_key 
            description: key of the campaign
          - name: camPGN_name
            description: name of the campaign
          - name: ads_cost
          - name: impression
            description: number of impressions
          - name: click
            description: number of clicks 
      - name: ads_criteo
        identifier: raw_gz_criteo
        description: campaigns on criteo/ one row per day with campaign key and name 
        columns: 
          - name: date_date
            description: date
          - name: paid_source
            description: campaign platform/ bing 
          - name: campaign_key 
            description: key of the campaign 
          - name: camPGN_name
            description: name of the campaign
          - name: ads_cost
            description: advertisement cost for the campaign on a specific day
          - name: impression
            description: number of impressions
          - name: click
            description: number of clicks 
      - name: ads_facebook
        identifier: raw_gz_facebook
        description: campaigns on facebook/ one row per day with campaign key and name
        columns:
          - name: date_date
            description: date
          - name: paid_source
            description: campaign platform/ bing 
          - name: campaign_key 
            description: key of the campaign 
          - name: camPGN_name
            description: name of the campaign
          - name: ads_cost
            description: advertisement cost for the campaign on a specific day
          - name: impression
            description: number of impressions
          - name: click
            description: number of clicks 

models: 
  - name: int_campaigns
    tests:
    - unique:
        column_name: "(date_date || '-' || campaign_name)" 
    - not_null: 
        column_name: "(date_date || '-' || campaign_name)" 
    columns:
      - name: date_date
        description: date
      - name: paid_source
        description: name of the advertisement source
      - name: campaign_key
        description: key for the campaign
      - name: campaign_name
        description: name of the campaign 
      - name: ads_cost
        description: cost of the campaign
        data_tests:
          - positive_values
      - name: impression
        description: number of impressions
      - name: click 
        description: number of clicks 
    

 
          


          




